@BookStore_HostAddress = http://localhost:5109
#cadastro valido
POST {{BookStore_HostAddress}}/author/
Accept: application/json
Content-Type: application/json

{
  "name": "new author",
  "email" : "newauthor@gmail.com",
  "description" : "descrição de informações para o novo autor"
}
###
#cadastro invalido
POST {{BookStore_HostAddress}}/author/
Accept: application/json
Content-Type: application/json

{
  "name": "",
  "email" : "newauthor@gmail.com",
  "description" : ""
}
###

POST {{BookStore_HostAddress}}/category/
Accept: application/json
Content-Type: application/json

{
  "name": "new category"
}

###
POST {{BookStore_HostAddress}}/book/
Accept: application/json
Content-Type: application/json

{
  "title": "Título do Livro 3",
  "resume": "Resumo do Livro",
  "summary": "Sumário do Livro",
  "price": 2500,
  "pages": 200,
  "isbn": "978-3-16-148410-3",
  "publishDate": "2024-04-01",
  "categoryId": 1,
  "authorId": 1
}
###
GET {{BookStore_HostAddress}}/book/
Accept: application/json
Content-Type: application/json
###
GET {{BookStore_HostAddress}}/book/1/
Accept: application/json
Content-Type: application/json
###
POST {{BookStore_HostAddress}}/country/
Accept: application/json
Content-Type: application/json

{
  "name": "Brasil"
}
###
POST {{BookStore_HostAddress}}/state/
Accept: application/json
Content-Type: application/json

{
  "name": "Amazonas",
  "countryId": 1
}