@BookStore_HostAddress = http://localhost:5109
#cadastro valido
POST {{BookStore_HostAddress}}/author/
Accept: application/json
Content-Type: application/json

{
  "name": "new author",
  "email" : "newauthor@gmail.com",
  "description" : "descrição de informações para o novo autor"
}
###
#cadastro invalido
POST {{BookStore_HostAddress}}/author/
Accept: application/json
Content-Type: application/json

{
  "name": "",
  "email" : "newauthor@gmail.com",
  "description" : ""
}
###

POST {{BookStore_HostAddress}}/category/
Accept: application/json
Content-Type: application/json

{
  "name": "new category"
}

###
POST {{BookStore_HostAddress}}/book/
Accept: application/json
Content-Type: application/json

{
  "title": "Título do Livro 4",
  "resume": "Resumo do Livro ",
  "summary": "Sumário do Livro ",
  "price": 2999,
  "pages": 200,
  "isbn": "978-3-16-148410-6",
  "publishDate": "2024-04-01",
  "categoryId": 1,
  "authorId": 1
}
###
GET {{BookStore_HostAddress}}/book/
Accept: application/json
Content-Type: application/json
###
GET {{BookStore_HostAddress}}/book/2/
Accept: application/json
Content-Type: application/json
###
POST {{BookStore_HostAddress}}/country/
Accept: application/json
Content-Type: application/json

{
  "name": "Brasil"
}
###
POST {{BookStore_HostAddress}}/state/
Accept: application/json
Content-Type: application/json

{
  "name": "Amazonas",
  "countryId": 1
}
###
POST {{BookStore_HostAddress}}/sale
Content-Type: application/json

{
  "Email": "user@example.com",
  "Name": "John",
  "Surname": "Doe",
  "Document": "12345678901",
  "Address": "1243 Main St",
  "Complement": "Apartment 4B",
  "City": "Springfield",
  "CountryId": 35,
  "PhoneNumber": "+123456789",
  "PostalCode": "12345",
  "OrderData": {
    "total": 25.00,
    "itens":[
      {
        "idLivro":1,
        "quantidade": 1
      }
    ]
  },
  "Cupon":"CUPON90"
}

###
POST {{BookStore_HostAddress}}/cupon
Content-Type: application/json

{
  "Code": "CUPON90",
  "Percentage": 90,
  "ExpiresAt": "2024-12-24"
}
